name = "food-days-api"
main = "src/index.ts"
compatibility_date = "2022-05-14"

kv_namespaces = [
    { binding = "FOOD_DAYS", id = "2411990cc7c1441a8009f9dfc3dab021", preview_id = "944393da0e4647fc9e592fb70363fa2e" },
]